version: "3.9"

services:
  client:
    container_name: "client"
    build: 
      context: "./my-project"
    ports:
      - "3000:3000"
  server:
    container_name: "server"
    restart: always
    build: 
      context: "./my-server"
    ports:
      - "8080:8080"